name: mesmer-tests

channels:
  - conda-forge
  - nodefaults

dependencies:
 - cartopy
 - dask
 - filefisher
 - joblib
 - matplotlib-base
 - nc-time-axis
 - netcdf4
 - numpy
 - packaging
 - pandas>=2.2
 - pooch
 - properscoring
 - pyproj
 - regionmask>=0.12
 - scikit-learn
 - scipy<=1.15.3, # https://github.com/statsmodels/statsmodels/issues/9542
 - statsmodels>=0.14
 - xarray>=2025.03
# for testing
 - black!=23
 - pytest
 - pytest-cov
 - pytest-xdist
 - ruff
