name: mesmer-tests

channels:
  - conda-forge
  - nodefaults

dependencies:
 - cartopy
 - dask[complete]
 - gdal
 - netcdf4
 - numpy
 - packaging
 - pandas<2.0
 - regionmask>=0.8
 - scikit-learn
 - sphinx
 - statsmodels
 - xarray
# for testing
 - black<23.1
 - flake8
 - isort
 - pytest
 - pytest-cov
