name: mesmer-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9
  - black
  - cartopy
  - cython
  - dask[complete]
  - flake8
  - gdal
  - isort
  - netcdf4
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - pytest-xdist
  - scikit-learn
  - statsmodels
  - regionmask
  - xarray
# required for docs
  - sphinx-book-theme
  - numpydoc
  - ipython
