name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: py${{ matrix.python-version }} ${{ matrix.os }} ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    if: |
      github.repository == 'MESMER-group/mesmer'
      && (github.event_name == 'push' || github.event_name == 'pull_request')
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.13"]
        env: [""]
        include:
          - env: "min-all-deps"
            python-version: "3.11"
            os: "ubuntu-latest"
          - env: ""
            python-version: "3.13"
            os: "macos-latest"
          - env: ""
            python-version: "3.13"
            os: "windows-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set environment variables
      run: |

        if [[ "${{ matrix.env }}" == "" ]]; then
          echo "CONDA_ENV_FILE=environment.yml" >> $GITHUB_ENV
        else
          echo "CONDA_ENV_FILE=ci/requirements/${{ matrix.env }}.yml" >> $GITHUB_ENV
        fi

    - name: Create conda environment
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: mesmer-tests
        cache-downloads: true
        cache-downloads-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{ env.CONDA_ENV_FILE }}"
        micromamba-version: 'latest'
        environment-file: ${{ env.CONDA_ENV_FILE }}
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Environment info
      run: |
        echo "numpy.show_config()"
        echo ""
        python -c "import numpy; numpy.show_config()"
        echo ""
        echo "Number of cpus and threads"
        python -c "import psutil; print(f'cpus: {psutil.cpu_count(logical=False)}; threads: {psutil.cpu_count()}')"
        echo ""
        echo "threadpool info:"
        python -c "import numpy; import threadpoolctl; print(threadpoolctl.threadpool_info())"

    - name: Install mesmer
      run: |
        python -m pip install --no-deps -e .

    - name: Run tests
      run: python -u -m pytest
       -n 2
       -r a -v
       --all
       --cov=mesmer
       --cov-report=xml

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
          file: ./coverage.xml
          flags: unittests
          env_vars: RUNNER_OS,PYTHON_VERSION
          name: codecov-umbrella
          fail_ci_if_error: false

  # ====================================================================================

  min-version-policy:
    name: Minimum Version Policy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - uses: xarray-contrib/minimum-dependency-versions@v0.1.1
        with:
          policy: ci/minimum-dependency-versions-policy.yml
          environment-paths: |
            ci/requirements/min-all-deps.yml
